site_name: Sonradan Öğrendiklerim
site_author: Eren Türkay
site_url: https://sonradanogrendiklerim.com

#repo_name: sonradanogrendiklerim
#repo_url: https://github.com/sonradanogrendiklerim/sonradanogrendiklerim.github.io/tree/src

copyright: Copyright &copy; 2024 Eren Türkay

nav:
  - Anasayfa: index.md
  - Bilgisayar Mühendisliğine Giriş:
      - Ön Söz: bilgisayar-muhendisligine-giris/index.md
      - Başlarken: bilgisayar-muhendisligine-giris/baslarken.md

      - Nasıl Soru Sorulur?:
          - Giriş: nasil-soru-sorulur/index.md
          - Sormadan Önce: nasil-soru-sorulur/sormadan-once.md
          - Soru Sorduğunuzda: nasil-soru-sorulur/soru-sordugunuzda.md

      - Linux:
          - Ubuntu Kurulumu: linux/ubuntu-kurulumu.md
          - Terminal: linux/terminal.md
          - Terminali Güzelleştirelim: linux/terminali-guzellestirelim.md
          - Fish Terminal Eklentileri: linux/fish-terminal-eklentileri.md
          - Terminal Komutu Nasıl Çalışır: linux/terminal-komutu-nasil-calisir.md

      - Python:
          - "Programlama Dili: Neden ve Nasıl": python/programlama-dili-neden-ve-nasil.md
          - Python'a Giriş ve Modern Geliştirme: python/pythona-giris-ve-modern-gelistirme.md
          - VSCode ile Python Geliştirme Ortamı: python/vscode-ile-python-gelistirme-ortami.md
          - Python Modül Yapısı: python/python-modul-yapisi.md

  - Makaleler:
      - Ana Sayfa: makaleler/index.md
      - Outline Güncelleme: makaleler/outline-guncelleme.md
      - "Notion Alternatifi: Outline Kurulumu": makaleler/notion-alternatifi-outline-kurulumu.md
      - Tailscale ile VPN Sunucusu Kurulumu: makaleler/tailscale-ile-vpn-sunucusu-kurulumu.md
      - Github Pages ile Statik Sayfa Sunmak: makaleler/github-pages-statik-sayfa.md

  - Blog: blog/index.md
  - İletişim: https://erenturkay.com/iletisim
  - Resume: https://erenturkay.com/assets/resume/Eren_Turkay_Resume.pdf

theme:
  name: material
  language: tr

  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: white
    accent: orange

  features:
    - navigation.top
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.footer
    - toc.follow
    - content.code.copy

  # Yorum eklentisini eklemek için gerekli
  custom_dir: overrides

markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - social
  - search
  - blog:
      pagination: true
      pagination_per_page: 7
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  analytics:
    provider: google
    property: G-E9CRJC3RBF

extra_css:
  - css/extra.css
